
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8089
    connection-timeout: 5000
    context-path: /qz_sjcs

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true


ismp:
     # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
    jwt:
        # 加密秘钥
        secret: a6e05afdf596a8e7fd8df7479d1919dc
        # token有效时长，单位秒
        expire: 604800
        header: token
    basePath: /tmp/